apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-service
  description: A sample Python microservice with FastAPI
  annotations:
    github.com/project-slug: your-org/python-service
    backstage.io/techdocs-ref: dir:.
  tags:
    - python
    - fastapi
    - microservice
    - rest-api
  links:
    - url: https://your-service-url.com
      title: Service URL
      icon: web
    - url: https://your-docs-url.com
      title: Documentation
      icon: docs
spec:
  type: service
  lifecycle: experimental
  owner: platform-team
  system: core-services
  providesApis:
    - python-service-api
  consumesApis: []
  dependsOn:
    - resource:database
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: python-service-api
  description: REST API for the Python service
spec:
  type: openapi
  lifecycle: experimental
  owner: platform-team
  system: core-services
  definition: |
    openapi: 3.0.3
    info:
      title: Python Service API
      version: 1.0.0
      description: A sample REST API built with FastAPI
    paths:
      /health:
        get:
          summary: Health check endpoint
          responses:
            '200':
              description: Service is healthy
      /api/v1/items:
        get:
          summary: Get all items
          responses:
            '200':
              description: List of items
        post:
          summary: Create a new item
          responses:
            '201':
              description: Item created successfully
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: database
  description: PostgreSQL database for the Python service
spec:
  type: database
  lifecycle: production
  owner: platform-team
  system: core-services
